apiVersion: v1
kind: Namespace
metadata: 
  name: production

---

apiVersion: v1
kind: Service
metadata:
  name: pdf-upload-backend
  namespace: production
  labels:
    app: pdf-upload-backend
spec:
  selector:
    app: pdf-upload-backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-upload-backend
  namespace: production
spec:
  selector:
    matchLabels:
      app: pdf-upload-backend
  strategy:
    type: RollingUpdate
  template: #Template for container
    metadata:
      labels:
        app: pdf-upload-backend
    spec:
      containers:
      - name: pdf-upload-backend
        image:  asia.gcr.io/pipelines-420101/production/pdf-upload-backend:$SHORT_SHA
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: backend-port
        resources:
          requests:
            cpu: 50m

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pdf-upload-backend
  namespace: production
spec:
  maxReplicas: 25
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pdf-upload-backend
  targetCPUUtilizationPercentage: 100

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pdf-upload-backend
  namespace: production
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: pdf-upload-backend
                port:
                  number: 3000
  ingressClassName: "nginx"